### ISSUE TITLE
Enable data at rest encryption

### ISSUE THREAD

**Issue by ntaphadrian** [NetAppDocs/cloud_volumes#112]
Page: [Creating a cloud volume](https://docs.netapp.com/us-en/cloud_volumes/aws/task_creating_cloud_volumes_for_aws.html)

We have a section that says to enable encryption - turn on SMB3 encryption.
But what about data at rest encryption, is it enabled by default behind the scenes.

Hadrian

**Comment by netapp-juliec** [comment]
Routed this comment to CVS for AWS product manager, Graham Smith.  Here's the response: 
>The online user docs are not a marketing document and we shouldn't list all 101 features on this page. 

close #112
