### ISSUE TITLE
Please update the throughput maximums in the 

### ISSUE THREAD

**Issue by mchad1** [NetAppDocs/cloud_volumes#120]
Please update the throughput maximums.  New numbers are out showing that CVS can go as far as  4,500MiB/s:

That means that for extreme, the new max is reached at 36TiB.
For Premium the new max is reached at 72TiB.

Please update accordingly in the page
https://docs.netapp.com/us-en/cloud_volumes/aws/reference_selecting_service_level_and_quota.html

**Comment by netapp-tonacki** [comment]
Hi, Updated the What's New and chart for service levels and quota on Aug 13 for this comment.
