### ISSUE TITLE
Add how to modify the number of inodes

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/cloud_volumes#129]
Page: [Modifying a cloud volume](https://docs.netapp.com/us-en/cloud_volumes/aws/task_modifying_cloud_volumes_for_aws.html)

This is documented in the 'what's new' section but it's not captured anywhere else. From the release notes, it says that there's a starting point but I'd like to see it in Modifying Volumes too.

(From release notes: "The maximum file count is increased by 20 million for each Terabyte allocated up to 100 million. The maximum may be increased to higher than 100 million via a customer support request.")

**Comment by netapp-tonacki** [comment]
Hi Phoebe, Thanks for the comment.   I updated the Creating topic, Modifying topic, and added a new sub-section about inodes in the topic https://docs.netapp.com/us-en/cloud_volumes/aws/reference_selecting_service_level_and_quota.html#allocated-capacity. Please take a look when you get a chance and let me know what you think.

**Comment by phoebegoh** [comment]
Hi Tom, thanks - that looks great. Really like how it's in a list. Though should the last point be >4 TB to **100** TB = 100 million inodes?

**Comment by netapp-tonacki** [comment]
yes, good catch Phoebe.  i will update that tomorrow.

**Comment by netapp-tonacki** [comment]
This was updated late last year.
