### ISSUE TITLE
Bad link to AWS Marketplace

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud_volumes#145]
Page: [What’s new in Cloud Volumes Service for AWS](https://docs.netapp.com/us-en/cloud_volumes/aws/reference_whats_new_cloud_volumes_aws.html)

This link to the AWS Marketplace on this page is dead:

 February 2020
The NetApp Cloud Volumes Service is now available as a Metered (pay as you go) subscription in the AWS Marketplace. See the Marketplace listing for more details at: https://aws.amazon.com/marketplace/pp/B0848MXK74
Note that the original monthly and annual subscription plans are still available.

**Comment by netapp-tonacki** [comment]
Hi mimitche, Not all AWS regions have been updated with the functionality for metering yet, so users currently need to be whitelisted to see this page. The plan is to make the link public early next week. Sorry that the link is not working for you.  Do you want me to tell you when it is live/public?

**Comment by netapp-tonacki** [comment]
This appears to be working in all regions now.
