### ISSUE TITLE
404 after unsuccessful search in AWS section

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/cloud_volumes#159]
1) Search for something https://docs.netapp.com/us-en/cloud_volumes/aws/search.html?q=sean

2) On the results page click on CVS to return to "home"

![image](https://user-images.githubusercontent.com/16622642/95051532-fcb47e80-071f-11eb-96df-44314b9a2343.png)

3) That results in a 404 error because the link is https://docs.netapp.com/us-en/cloud_volumes/ and it should be https://docs.netapp.com/us-en/cloud_volumes/aws/ (as mentioned above originally I was on the AWS version)

**Comment by netapp-tonacki** [comment]
Hi,  Thanks for the comment.  That's a good catch.  Not sure why that happens, but we'll take a look at this and get back to you.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi, We were able to find what the issue was and it has been corrected.  thanks for bringing this to our attention.

Tom
