### ISSUE TITLE
Keep the "What's new" section up-to-date | Documentation is too shallow

### ISSUE THREAD

**Issue by si-heger** [NetAppDocs/cloud_volumes#70]
Page: [What’s new in Cloud Volumes Service for AWS](https://docs.netapp.com/us-en/cloud_volumes/aws/reference_whats_new_cloud_volumes_aws.html)

If the "What's new" section should be what it means then maybe add what is new :)

Example:
- November 2018: Go Live of Cloud Volume Service for AWS in Frankfurt, Dublin ....

Documentation is missing details in many areas:
- General implementation details: E. g. that a volume is always 100 TB thin provisioned on the client side
- What are the SLAs for the service (availability, durability)?
- What are the limits (in terms of scale, performance, configuration)? e. g. that per AWS Account you can only use it in 10 VPCs as that is the limit of the Virtual Interfaces with the Direct Connect; that you can only create 5 NFS Export Policies
- General Performance Details (e. g. max. 4.5 GB throughput of Egress because of the Virtual Private Gateway; latency in the different regions)

These are just small examples. If you compare it to the documentation of Amazon AWS EFS then ours is quite high-level ...

**Comment by netapp-tonacki** [comment]
Hi Simon,  Thanks for the comments.  I brought up your concerns to some other folks on the team. I have made some updates to the What's New to indicate support in new AWS regions and to list SMB 2.1 as supported in the Nov release.

Most of the other information you mentioned already exists in the FAQ, so we are discussing whether we should integrate some of the information into the user docs from the FAQ, or if we should add a link to the FAQ from the user docs.  We need to verify if all FAQ content is customer ready.

Thanks, Tom

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @si-heger - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
