### ISSUE TITLE
Possible values for `lifeCycleState`?

### ISSUE THREAD

**Issue by shawnr** [NetAppDocs/cloud_volumes#73]
I cannot find any documentation listing the possible values for `lifeCycleState` in the CVS API response. The property is mentioned, but only the `"available"` state is shown.

It is mentioned on this page: https://github.com/NetAppDocs/cloud_volumes/blob/master/aws/reference_cloud_volume_apis.adoc

I would like to know all values and associated text descriptions for the `lifeCycleState` values.

**Comment by netapp-tonacki** [comment]
Hi Shawn,  Thanks for your question.  I checked in the API and this is what is listed:

lifeCycleState:
        description: The current lifecycle state of the resource
        type: string
        title: lifeCycleState
        enum:
          - creating
          - available
          - updating
          - disabled
          - deleting
          - deleted
          - error

**Comment by shawnr** [comment]
Thanks for the info @netapp-tonacki
