### ISSUE TITLE
Available regions?

### ISSUE THREAD

**Issue by shawnr** [NetAppDocs/cloud_volumes#74]
Is there a way to discover available regions through the CVS API? Or is there documentation of which regions are supported (other than the drop-down menu in the CVS interface)?

**Comment by netapp-tonacki** [comment]
Hi Shawn, The [What's New](https://docs.netapp.com/us-en/cloud_volumes/aws/reference_whats_new_cloud_volumes_aws.html) topic was recently updated with the currently supported regions.

I don't know of any way to find a list of available regions using the API.

**Comment by shawnr** [comment]
Thanks for the info. I'll keep an eye there.

**Comment by netapp-tonacki** [comment]
Shawn,  I still don't know of any way to get this info from the API, but there is a new page https://cloud.netapp.com/cloud-volumes-global-regions where you can choose the product and see all the regions.

**Comment by brint** [comment]
Looks like there still isn't a way to get all regions from the API. There is a call to get regions, but it only pulls back the region you call:

https://app.swaggerhub.com/apis/NetApp-Cloud/c-vaa_s/1.1.2#/storage/v2_listRegions

Real call:

```
$ curl -s -H accept:application/json  -H "Content-type: application/json"  -H api-key:$API_KEY  -H secret-key:$SECRET_KEY  -X GET https://cds-aws-bundles.netapp.com:8080/v2/Storage/Regions | jq
[
  {
    "UUID": "f99286e2-600d-0910-a768-2cda34a705c0",
    "createdAt": "2018-04-16T11:47:46.000Z",
    "name": "us-east-1",
    "updatedAt": "2018-12-19T15:15:40.000Z"
  }
]
```

It would be nice to be able to get a list of regions and include the API endpoints in the region list response since API endpoints differ for us-east-1 versus all the other CVS regions.

**Comment by netapp-tonacki** [comment]
Hi,  Thanks for the feedback.  This is on the enhancement list to create a centralized endpoint instead of each CVS/AWS region having a separate URL endpoint.  But I do not know the time frame when this will happen.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @shawnr - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
